name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: build with sizemode
        run: pnpm run build:size
      - name: checksize
        run: pnpm run showsize  >> $GITHUB_STEP_SUMMARY
      - name: upload dist to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
